name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch
  pull_request:  # Also trigger on pull requests
    branches:
      - main

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maven_build:
    strategy:
      matrix:
        version: [11, 8]  # Ensure your project supports these versions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK "${{ matrix.version }}"
        uses: actions/setup-java@v3
        with:
          java-version: "${{ matrix.version }}"
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

